name: javascript

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Check Out Repository
          uses: actions/checkout@v4

        # - name: Lint
        #   uses: pnpm run lint
            
